### ISSUE TITLE
Tab space in DDTL

### ISSUE THREAD

**Issue by nsavic89** [kyouko-taiga/trexmo#3]
The new version does not 'like' tabs within the DDTLs. If I use tabs to define a field in a DDTL file and run the tool, an error shows ('JSON' something). Once I replace the tab separation with four spaces it works.

**Comment by kyouko-taiga** [comment]
Python doesn't support mixing tabs and spaces. As everything else in TREXMO is written with a 4 spaces indentation, I suggest you get along with DDTL files.
